apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-argocd
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

--- 
### This rolebinding solves the below error.
### services is forbidden: User "system:serviceaccount:openshift-gitops:argocd-cluster-argocd-application-controller" cannot create resource "services" in API group "" in the namespace "ilender-dev-ns"
